In [1]:
ls data

 Volume in drive C is OS
 Volume Serial Number is C855-57FA

 Directory of C:\Users\DejunChen\Desktop\cms-workshop\data

05/08/2019  12:18 PM    <DIR>          .
05/08/2019  12:18 PM    <DIR>          ..
05/08/2019  12:20 PM               619 benzene.xyz
05/08/2019  12:18 PM             2,471 buckminsterfullerene.xyz
02/19/2019  10:37 AM           355,359 distance_data_headers.csv
05/08/2019  12:14 PM    <DIR>          outfiles
02/19/2019  10:29 AM            61,568 sapt.out
01/29/2019  04:02 PM               155 water.xyz
               5 File(s)        420,172 bytes
               3 Dir(s)  174,946,537,472 bytes free


In [7]:
import os
import numpy
file_location = os.path.join('data', 'water.xyz')

data = numpy.genfromtxt(fname=file_location, dtype='unicode', skip_header=2)

print(data)

[['O' '0.000000' '-0.007156' '0.965491']
 ['H1' '-0.000000' '0.001486' '-0.003471']
 ['H2' '0.000000' '0.931026' '1.207929']]


In [8]:
print(data[2])

['H2' '0.000000' '0.931026' '1.207929']


In [9]:
data2 = data[:, 1:]
print(data2)

[['0.000000' '-0.007156' '0.965491']
 ['-0.000000' '0.001486' '-0.003471']
 ['0.000000' '0.931026' '1.207929']]


In [10]:
data3 = data2.astype(numpy.float)
print(data3)

[[ 0.       -0.007156  0.965491]
 [-0.        0.001486 -0.003471]
 [ 0.        0.931026  1.207929]]


In [11]:
num_atoms = len(data[:,0])
print(num_atoms)

3


In [16]:
for i in range(0, num_atoms):
    x1, y1, z1 = data3[i, 0], data3[i, 1], data3[i, 2]
    for j in range(0, num_atoms):
        print(i)
        print(j)
        x2, y2, z2 = data3[j, 0], data3[j, 1], data3[j, 2]
        sqdistance = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
        distance = numpy.sqrt(sqdistance)
        print(F'{data[i,0]} to {data[j,0]} distance is: {distance}')


0
0
O to O distance is: 0.0
0
1
O to H1 distance is: 0.9690005374652793
0
2
O to H2 distance is: 0.9690003348647513
1
0
H1 to O distance is: 0.9690005374652793
1
1
H1 to H1 distance is: 0.0
1
2
H1 to H2 distance is: 1.52693633514957
2
0
H2 to O distance is: 0.9690003348647513
2
1
H2 to H1 distance is: 1.52693633514957
2
2
H2 to H2 distance is: 0.0


In [17]:
for i in range(0, num_atoms):
    x1, y1, z1 = data3[i, 0], data3[i, 1], data3[i, 2]
    for j in range(0, num_atoms):
        print(i)
        print(j)
        if i==j: 
            continue
        x2, y2, z2 = data3[j, 0], data3[j, 1], data3[j, 2]
        sqdistance = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
        distance = numpy.sqrt(sqdistance)
        print(F'{data[i,0]} to {data[j,0]} distance is: {distance}')

0
0
0
1
O to H1 distance is: 0.9690005374652793
0
2
O to H2 distance is: 0.9690003348647513
1
0
H1 to O distance is: 0.9690005374652793
1
1
1
2
H1 to H2 distance is: 1.52693633514957
2
0
H2 to O distance is: 0.9690003348647513
2
1
H2 to H1 distance is: 1.52693633514957
2
2


In [18]:
for i in range(0, num_atoms):
    x1, y1, z1 = data3[i, 0], data3[i, 1], data3[i, 2]
    for j in range(0, num_atoms):
        print(i)
        print(j)
        if i==j: 
            continue
        x2, y2, z2 = data3[j, 0], data3[j, 1], data3[j, 2]
        sqdistance = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
        distance = numpy.sqrt(sqdistance)
        if distance > 1.5:
            print(F'{data[i,0]} to {data[j,0]} distance is: {distance} and no bonding')
            continue
        print(F'{data[i,0]} to {data[j,0]} distance is: {distance}')

0
0
0
1
O to H1 distance is: 0.9690005374652793
0
2
O to H2 distance is: 0.9690003348647513
1
0
H1 to O distance is: 0.9690005374652793
1
1
1
2
H1 to H2 distance is: 1.52693633514957 and no bonding
2
0
H2 to O distance is: 0.9690003348647513
2
1
H2 to H1 distance is: 1.52693633514957 and no bonding
2
2


In [20]:
for i in range(0, num_atoms):
    x1, y1, z1 = data3[i, 0], data3[i, 1], data3[i, 2]
    for j in range(0, num_atoms):
        print(i)
        print(j)
        if i==j: 
            print(F'{data[i,0]} to {data[j,0]} is the same atom')
            continue
        x2, y2, z2 = data3[j, 0], data3[j, 1], data3[j, 2]
        sqdistance = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
        distance = numpy.sqrt(sqdistance)
        if distance > 1.5:
            print(F'{data[i,0]} to {data[j,0]} distance is {distance} over 1.5 and no bonding')
            continue
        print(F'{data[i,0]} to {data[j,0]} distance is: {distance}')

0
0
O to O is the same atom
0
1
O to H1 distance is: 0.9690005374652793
0
2
O to H2 distance is: 0.9690003348647513
1
0
H1 to O distance is: 0.9690005374652793
1
1
H1 to H1 is the same atom
1
2
H1 to H2 distance is 1.52693633514957 over 1.5 and no bonding
2
0
H2 to O distance is: 0.9690003348647513
2
1
H2 to H1 distance is 1.52693633514957 over 1.5 and no bonding
2
2
H2 to H2 is the same atom


In [23]:
for i in range(0, num_atoms):
    x1, y1, z1 = data3[i, 0], data3[i, 1], data3[i, 2]
    for j in range(0, num_atoms):
        print(i)
        print(j)
        if j>i: 
            x2, y2, z2 = data3[j, 0], data3[j, 1], data3[j, 2]
            sqdistance = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
            distance = numpy.sqrt(sqdistance)
            if distance > 1.5:
                print(F'{data[i,0]} to {data[j,0]} distance is {distance} over 1.5 and no bonding')
                continue
            print(F'{data[i,0]} to {data[j,0]} distance is: {distance}')
        else: 
            print(F'{data[i,0]} to {data[j,0]} is evaluated other way')

0
0
O to O is evaluated other way
0
1
O to H1 distance is: 0.9690005374652793
0
2
O to H2 distance is: 0.9690003348647513
1
0
H1 to O is evaluated other way
1
1
H1 to H1 is evaluated other way
1
2
H1 to H2 distance is 1.52693633514957 over 1.5 and no bonding
2
0
H2 to O is evaluated other way
2
1
H2 to H1 is evaluated other way
2
2
H2 to H2 is evaluated other way


In [26]:
outfile = open('bond_lengths.txt', 'w+')
for i in range(0, num_atoms):
    x1, y1, z1 = data3[i, 0], data3[i, 1], data3[i, 2]
    for j in range(0, num_atoms):
        #print(i)
        outfile.write(F'i={i}, j={j} \n')
        #print(j)
        if j>i: 
            x2, y2, z2 = data3[j, 0], data3[j, 1], data3[j, 2]
            sqdistance = (x1-x2)**2 + (y1-y2)**2 + (z1-z2)**2
            distance = numpy.sqrt(sqdistance)
            if distance > 1.5:
                outfile.write(F'{data[i,0]} to {data[j,0]} distance is {distance} over 1.5 and no bonding \n')
                #print(F'{data[i,0]} to {data[j,0]} distance is {distance} over 1.5 and no bonding')
                continue
            outfile.write(F'{data[i,0]} to {data[j,0]} distance is: {distance} \n')
            #print(F'{data[i,0]} to {data[j,0]} distance is: {distance}')
        else: 
            outfile.write(F'{data[i,0]} to {data[j,0]} is evaluated other way \n')
            #print(F'{data[i,0]} to {data[j,0]} is evaluated other way')
outfile.close()